### ISSUE TITLE
Undefined method `visit_constructor' for custom Hash constructor

### ISSUE THREAD

**Issue by rykov** [dry-rb/dry-schema#280]
**Describe the bug:**

It may be a regression, or an undocumented syntax change. I'm trying to coerce a JSON string param into a hash through a custom constructor. It worked in `1.4.3` but now fails in `1.5.0`.

The corresponding versions of `dry-types` pulled in by `dry-schema` were `1.2.2` and `1.4.0` respectively.

**To Reproduce:**

```ruby
require 'dry-schema'
require 'dry-types'
require 'json'

module Types
  include Dry.Types()
  JSONHash = Types::Hash.constructor do |h|
    h.is_a?(::Hash) ? h : ::JSON.parse(h)
  end
end

Schema = Dry::Schema.Params do
  required(:foo).filled(Types::JSONHash)
end

h = Schema.call(foo: %q({ "hello": "hi" })).to_h
puts "#{h[:foo].class.name} -- #{h[:foo].inspect}"
```

With dry-schema 1.4.3, here's the output

    Hash -- {"hello"=>"hi"}

With dry-schema 1.5.0, I get this:

    ...
    undefined method `visit_constructor' for #<Dry::Schema::Compiler:0x00007fc2ba917858> (NoMethodError)
    Did you mean?  visit_attr

**Expected behavior**

Behavior described above for 1.4.3 seems correct. 

**Your environment**

- Affects my production application: **YES**
- Ruby version: ruby 2.7.1p83
- macOS Catalina

**Comment by solnic** [comment]
oh noez! :/ thanks for the report, I'll fix it in 1.5.1

**Comment by AlexVPopov** [comment]
Hey @solnic, can this be closed, has this been fixed in >= 1.5.4?

**Comment by rykov** [comment]
@AlexVPopov @solnic It's still a problem with the following versions:

```ruby
gem 'dry-schema', '1.5.4'
gem 'dry-types', '1.4.0'
```

**Comment by solnic** [comment]
@flash-gordon 👋 do you happen to remember what we concluded wrt handling constructors here? 😅

**Comment by flash-gordon** [comment]
@solnic I'm pretty sure this is intentionally not supported. It may work in simpler cases but then something like `my_fancy_type = hash_type.schema(...).constuctor(...)`most certainly will fail.

**Comment by solnic** [comment]
@flash-gordon OK but couldn't we apply the type when it's not a hash schema? My understanding is that we can't infer rules from a schema hash that is also a constructor, right?

**Comment by flash-gordon** [comment]
@solnic sure, it's on the surface. Fixing this particular error shouldn't be a problem, but I didn't try. My concern is I saw a more substantial problem with constructors and schemas, but I don't remember what that was 😕

**Comment by solnic** [comment]
@flash-gordon yeah it's funny but now when I think about it, I can't see why we can't support that 😅 Primitive inferrer works just fine with hash constructors:

```ruby
dry-schema> inferrer[Dry::Schema::Types::Hash.schema(foo: "string").constructor(&:to_h)]
=> [Hash]
```

So it's a matter of rebuilting the type so that it only applies its constructor and using its schema just we do it now.

**Comment by rykov** [comment]
@solnic @flash-gordon following up - this is still a problem with:

```ruby
gem 'dry-schema', '1.6.1'
gem 'dry-types', '1.5.1'
```

**Comment by solnic** [comment]
I've set the milestone to 2.0.0 - in general, support for custom constructor-types should be improved. I'm repeating this to death but here it goes: we need to make type specs obligatory and simplify DSL implementation. This should make it easier to improve existing features. I don't recall what the exact problem is in this case, but I suspect it has something to do with deconstruction of types so that the schema can infer the types and then probably losing the actual constructor function in the process.

**Comment by midnight-wonderer** [comment]
Forget custom constructors.
It does not even work with built-in types.

Try:
~~~ruby
require 'dry-schema'
require 'dry-types'

module Types
  include Dry.Types()
end

Schema = Dry::Schema.Params do
  required(:foo).filled(Types::Params::Hash)
end
~~~

If I can follow the code, I would help with the issue; but I can't read the `dry-rb` code at all.  
Probably the issue is on me, or `dry-rb` might used too many Ruby features.

**Comment by flash-gordon** [comment]
There's no differentiation between "custom" and "built-in" types, constructor hash types are not working at the moment (though I'm not sure why).

**Comment by solnic** [comment]
So, like I mentioned a little...over...a year....ago....this was caused by the fact that a custom type would not be set in various cases. I gave it a shot to see if *at least* the scenarios mentioned in this issue can be addressed and I succeeded. I'm not too confident that this issue will go away 100% so I'll revisit this when working on 2.0.0.

For now, this specific issue (as in, the scenarios mentioned here) will be addressed in the upcoming 1.7.0 release.

**Comment by rykov** [comment]
@solnic Great news! Thank you for the fix.

**Comment by solnic** [comment]
> If I can follow the code, I would help with the issue; but I can't read the dry-rb code at all.
> Probably the issue is on me, or dry-rb might used too many Ruby features.

@midnight-wonderer don't worry about this, you jumped into *literally one of the most complicated codebases* in dry-rb land 🙂 The schema DSL has a lot of additional complexity because it still works with or without type specifications and this will be greatly simplified in 2.0.0 (if I had a penny every time I mention this...lol). Furthermore, debugging issues with types also requires knowledge about dry-types and that's a journey on its own. Then if you want to understand how predicates are handled, you'd need to understand dry-logic first.

If you take a look at the PR where I addressed the issue, you'll see that it was a one-file change. The trick is to know where to look 🙂
