### ISSUE TITLE
Arrays of Hashes breaks in v1.4.2

### ISSUE THREAD

**Issue by joelvh** [dry-rb/dry-schema#218]
**Describe the bug**

No code changes, just a dry-schema gem upgrade. Hash schemas have notoriously been problematic with dry-rb libraries and my workarounds break with every few releases. In dry-schema v1.4.1 everything works fine, but v1.4.2 introduces the notorious `NoMethodError: undefined method 'visit_schema' for #<Dry::Types::PredicateInferrer::Compiler:0x00007fdb4eb2c3f8>` error.

**To Reproduce**

This example reproduces the issue where it works in v1.4.1 and breaks in v1.4.2.

```ruby
# Types
T=Class.new{include Dry.Types(default: :nominal)}
# Custom type
UUID_V4=T::Strict::String.constrained(format: /\A[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-4[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}\z/i).constructor(&:to_s).meta(type: :UUID_V4)
# Hash schema in array
HASHES=T::Strict::Array.of(T::Hash.schema(field: UUID_V4, value: T::Strict::String))
# Contract which throws an error
C=Class.new(Dry::Validation::Contract) { params { required(:hashes).maybe(HASHES) } }
```

There are other cases in which I get this error, but this is one I was able to create a reproducible script for.

Semi-related: I've seen the dry-rb team say in threads elsewhere that complex Hashes aren't very supported.  I've gotten around those kinds of issues by wrapping complex Hash schemas inside a Hash constructor. I'm not doing that in the example above to reproduce the regression, but here's an example how I wrap Hash schemas elsewhere. Have yet to see if this is now also broken.

```ruby
T::Hash.constructor(T::Hash.schema(field: UUID_V4, value: T::String.constructor(&:to_s)))
```

**Expected behavior**

The expected behavior is that the contract doesn't throw an error building the predicates and can be used to validate a hash.

**Your environment**

- Affects my production application: **NO**
- Ruby version: 2.5.6p201
- OS: macOS Mojave

**Comment by solnic** [comment]
@joelvh I'm sorry you're having trouble. Which dry-types do you use? I have a feeling this was caused by recent changes there rather than dry-schema changes. Could you try it with dry-types `1.2.1`, `1.2.0` and `1.1.1`?

**Comment by joelvh** [comment]
@solnic i was using v1.2.2 -- v1.2.1 and 1.2.0 didn't work. to try v1.1.1, I had to downgrade dry-schema and dry-validation, which worked, but it was dry-schema v1.4.2 that broke things -- dry-schema v1.4.1 works.

**Comment by solnic** [comment]
@joelvh thanks, I'll look into this
